// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeO6G5lmJlf02XLYqtR7QFo7UZ0EjZXWk',
    appId: '1:647979977158:web:28723a091a4f3cc58fcac7',
    messagingSenderId: '647979977158',
    projectId: 'allyvalley-83',
    authDomain: 'allyvalley-83.firebaseapp.com',
    storageBucket: 'allyvalley-83.appspot.com',
    measurementId: 'G-G72JHL9YB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCykhjpeEYeFanVgSOsW4TnpjEsMtIidH4',
    appId: '1:647979977158:android:09cb150a9ee107938fcac7',
    messagingSenderId: '647979977158',
    projectId: 'allyvalley-83',
    storageBucket: 'allyvalley-83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzSgPW-UbGW-pHJsx5pPIQPP5UV5IS0Mo',
    appId: '1:647979977158:ios:840133c013c18a9c8fcac7',
    messagingSenderId: '647979977158',
    projectId: 'allyvalley-83',
    storageBucket: 'allyvalley-83.appspot.com',
    androidClientId: '647979977158-6o80gl5b2vc3kaa1aajejov5jcoam7al.apps.googleusercontent.com',
    iosClientId: '647979977158-caq81csjcd84pg9hgba7bt87qj6kfqau.apps.googleusercontent.com',
    iosBundleId: 'com.example.psythereum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzSgPW-UbGW-pHJsx5pPIQPP5UV5IS0Mo',
    appId: '1:647979977158:ios:840133c013c18a9c8fcac7',
    messagingSenderId: '647979977158',
    projectId: 'allyvalley-83',
    storageBucket: 'allyvalley-83.appspot.com',
    androidClientId: '647979977158-6o80gl5b2vc3kaa1aajejov5jcoam7al.apps.googleusercontent.com',
    iosClientId: '647979977158-caq81csjcd84pg9hgba7bt87qj6kfqau.apps.googleusercontent.com',
    iosBundleId: 'com.example.psythereum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeO6G5lmJlf02XLYqtR7QFo7UZ0EjZXWk',
    appId: '1:647979977158:web:18981ea5abcecb2f8fcac7',
    messagingSenderId: '647979977158',
    projectId: 'allyvalley-83',
    authDomain: 'allyvalley-83.firebaseapp.com',
    storageBucket: 'allyvalley-83.appspot.com',
    measurementId: 'G-KSMDKSBTGS',
  );
}
